name: cookbook

services:
  backend:
    image: cookbook-backend
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=username
      - DB_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=deploy
    volumes:
      - db-data:/app/data
    profiles: [ "deploy" ]

  frontend:
    image: cookbook-frontend
    ports:
      - "80:8081"
    depends_on:
      - backend
    profiles: [ "deploy" ]

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./model_files:/model_files
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "/scripts/run_ollama.sh"]
    profiles: [ "dev" ]

volumes:
  db-data:
  ollama-data: