spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

bedrock.model-id=eu.anthropic.claude-haiku-4-5-20251001-v1:0
bedrock.region=eu-north-1

bedrock.aws-access-key-id=${BEDROCK_AWS_ACCESS_KEY_ID}
bedrock.aws-secret-access-key=${BEDROCK_AWS_SECRET_ACCESS_KEY}

frontend.url=https://d64m1ytsn90cc.cloudfront.net/